# Generated by Django 4.2.8 on 2024-04-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='user_uuid',
            new_name='id',
        ),
    ]
