# Generated by Django 4.2.8 on 2024-05-02 10:21

from django.db import migrations, models
import user.utils.utils
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_rename_user_uuid_myuser_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="myuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="fullname",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Полное имя"
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=user.utils.utils.user_image_path,
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активный"),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Персонал"),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="Суперпользователь"),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Имя пользователя",
            ),
        ),
    ]
