# Generated by Django 4.2.8 on 2024-05-16 19:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import promotion.utils.discount_validate
import promotion.utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_alter_workschedule_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slider_image', models.ImageField(upload_to='promotion/slides/%Y-%m-%d/', verbose_name='Изображение для слайдера')),
                ('old_price', models.PositiveIntegerField(null=True, verbose_name='Старая цена')),
                ('new_price', models.PositiveIntegerField(verbose_name='Новая цена')),
                ('discount', models.PositiveIntegerField(null=True, validators=[promotion.utils.discount_validate.validate_discount], verbose_name='Скидка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type', models.CharField(choices=[('Discount', 'Скидка'), ('Bonus', 'Бонус'), ('Certificate', 'Сертификат'), ('Draw', 'Розыгрыш')], default='Discount', max_length=45, verbose_name='Тип')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_daily', models.BooleanField(default=False, verbose_name='Ежедневно')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='WhatsApp')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Веб-сайт')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'db_table': 'promotion',
            },
        ),
        migrations.CreateModel(
            name='PromotionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to=promotion.utils.utils.category_image_path, verbose_name='Изображение')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='promotion.promotion', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Изображение акции',
                'verbose_name_plural': 'Изображения акций',
                'db_table': 'promotion_image',
            },
        ),
        migrations.CreateModel(
            name='PromotionContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_contact', to='promotion.promotion', verbose_name='К какой акции относиться')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номер телефона',
            },
        ),
        migrations.CreateModel(
            name='PromotionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to=promotion.utils.utils.category_image_path, verbose_name='Изображение')),
                ('icon', models.FileField(blank=True, null=True, upload_to=promotion.utils.utils.category_icon_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='Иконка')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='promotion.promotioncategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория акции',
                'verbose_name_plural': 'Категории акций',
                'db_table': 'promotion_category',
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='promotion.promotioncategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_promotions', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_promotions', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
