# Generated by Django 4.2.8 on 2024-05-17 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='website',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='whatsapp',
        ),
    ]
