# Generated by Django 4.2.8 on 2024-03-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promotion/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='slider_image',
            field=models.ImageField(blank=True, null=True, upload_to='promotion/slides/%Y-%m-%d/'),
        ),
    ]
