# Generated by Django 4.2.8 on 2024-04-17 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 22, 15, 48, 55, 552706)),
        ),
    ]
