# Generated by Django 4.2.8 on 2024-04-17 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_alter_promotion_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 22, 16, 26, 32, 304855)),
        ),
    ]
