# Generated by Django 4.2.8 on 2024-05-02 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import promotion.models
import promotion.utils.utils


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0003_alter_company_options_alter_contact_options_and_more"),
        ("promotion", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promotion",
            options={"verbose_name": "Акция", "verbose_name_plural": "Акции"},
        ),
        migrations.AlterModelOptions(
            name="promotioncategory",
            options={
                "verbose_name": "Категория акции",
                "verbose_name_plural": "Категории акций",
            },
        ),
        migrations.AlterModelOptions(
            name="promotionimage",
            options={
                "verbose_name": "Изображение акции",
                "verbose_name_plural": "Изображения акций",
            },
        ),
        migrations.AlterField(
            model_name="promotion",
            name="address",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="promotion.promotioncategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="company.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="discount",
            field=models.PositiveIntegerField(
                null=True,
                validators=[promotion.models.validate_discount],
                verbose_name="Скидка",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="end_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата окончания"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="facebook",
            field=models.URLField(blank=True, null=True, verbose_name="Facebook"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="promotion/%Y-%m-%d/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="instagram",
            field=models.URLField(blank=True, null=True, verbose_name="Instagram"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="is_daily",
            field=models.BooleanField(default=False, verbose_name="Ежедневно"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="liked_promotions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайки",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="new_price",
            field=models.PositiveIntegerField(verbose_name="Новая цена"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="old_price",
            field=models.PositiveIntegerField(null=True, verbose_name="Старая цена"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="slider_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="promotion/slides/%Y-%m-%d/",
                verbose_name="Изображение для слайдера",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="type",
            field=models.CharField(
                choices=[
                    ("Discount", "Скидка"),
                    ("Bonus", "Бонус"),
                    ("Certificate", "Сертификат"),
                    ("Draw", "Розыгрыш"),
                ],
                default="Discount",
                max_length=45,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Веб-сайт"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="whatsapp",
            field=models.URLField(blank=True, null=True, verbose_name="WhatsApp"),
        ),
        migrations.AlterField(
            model_name="promotioncategory",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=promotion.utils.utils.category_icon_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg"]
                    ),
                    promotion.models.validate_svg_size,
                ],
                verbose_name="Иконка",
            ),
        ),
        migrations.AlterField(
            model_name="promotioncategory",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=promotion.utils.utils.category_image_path,
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="promotioncategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="promotion.promotioncategory",
                verbose_name="Родительская категория",
            ),
        ),
        migrations.AlterField(
            model_name="promotioncategory",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="promotionimage",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=promotion.utils.utils.category_image_path,
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="promotionimage",
            name="promotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="promotion.promotion",
                verbose_name="Акция",
            ),
        ),
        migrations.AlterField(
            model_name="promotionimage",
            name="title",
            field=models.CharField(max_length=30, verbose_name="Название"),
        ),
    ]
