# Generated by Django 4.2.8 on 2024-04-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_alter_promotion_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='istagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
