# Generated by Django 4.2.8 on 2024-03-06 11:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import promotion.models
import promotion.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotioncategory',
            name='icon',
            field=models.FileField(null=True, upload_to=promotion.utils.utils.category_icon_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg']), promotion.models.validate_svg_size]),
        ),
        migrations.CreateModel(
            name='PromotionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to=promotion.utils.utils.category_image_path)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='promotion.promotion')),
            ],
            options={
                'verbose_name': 'promotion_image',
                'verbose_name_plural': 'promotion_images',
                'db_table': 'promotion_image',
            },
        ),
    ]
