# Generated by Django 4.2.8 on 2024-03-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='work_time',
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_time', to='promotion.promotion')),
            ],
            options={
                'verbose_name': 'work_time',
                'verbose_name_plural': 'work_times',
                'db_table': 'work_time',
            },
        ),
    ]
