# Generated by Django 4.2.8 on 2024-04-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_promotion_facebook_promotion_istagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='istagram',
            new_name='instagram',
        ),
    ]
