# Generated by Django 4.2.8 on 2024-04-06 19:19

import datetime
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import promotion.models
import promotion.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_promotion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktime',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='address',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='contacts',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 12, 1, 19, 7, 283261)),
        ),
        migrations.AlterField(
            model_name='promotioncategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=promotion.utils.utils.category_icon_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg']), promotion.models.validate_svg_size]),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='PromotionAddress',
        ),
        migrations.DeleteModel(
            name='WorkTime',
        ),
        migrations.AddField(
            model_name='promotion',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='contacts',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1, max_length=128, region=None),
            preserve_default=False,
        ),
    ]
