# Generated by Django 4.2.8 on 2024-05-18 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotion', '0003_promotion_facebook_promotion_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='user',
        ),
        migrations.AddField(
            model_name='promotion',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
