# Generated by Django 4.2.8 on 2024-05-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotion", "0003_alter_promotion_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotion",
            name="image",
        ),
        migrations.AlterField(
            model_name="promotion",
            name="end_date",
            field=models.DateTimeField(verbose_name="Дата окончания"),
        ),
    ]
