# Generated by Django 4.2.8 on 2024-05-05 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_alter_workschedule_options"),
        ("promotion", "0004_remove_promotion_image_alter_promotion_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.company",
                verbose_name="Компания",
            ),
        ),
    ]
