# Generated by Django 4.2.8 on 2024-05-10 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("promotion", "0005_alter_promotion_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="slider_image",
            field=models.ImageField(
                default=django.utils.timezone.now,
                upload_to="promotion/slides/%Y-%m-%d/",
                verbose_name="Изображение для слайдера",
            ),
            preserve_default=False,
        ),
    ]
