# Generated by Django 4.2.8 on 2024-05-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotion", "0006_alter_promotion_slider_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="slider_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="promotion/slides/%Y-%m-%d/",
                verbose_name="Изображение для слайдера",
            ),
        ),
    ]
