# Generated by Django 4.2.8 on 2024-05-10 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("promotion", "0007_alter_promotion_slider_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="favorite_promotions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Избранное",
            ),
        ),
    ]
