# Generated by Django 4.2.8 on 2024-01-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_time'], 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
    ]
