# Generated by Django 4.2.8 on 2024-05-02 10:21

import company.utils.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Компания", "verbose_name_plural": "Компании"},
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Контакт", "verbose_name_plural": "Контакты"},
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="company",
            name="discounts",
            field=models.PositiveIntegerField(verbose_name="Скидки"),
        ),
        migrations.AlterField(
            model_name="company",
            name="image",
            field=models.ImageField(
                upload_to=company.utils.utils.company_image_path,
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="company.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="title",
            field=models.CharField(max_length=50, unique=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="value",
            field=models.CharField(max_length=250, verbose_name="Значение"),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_schedule",
                to="company.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="friday_end",
            field=models.TimeField(blank=True, null=True, verbose_name="Конец Пятницы"),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="friday_start",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Начало Пятницы"
            ),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="monday_end",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Конец Понедельника"
            ),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="monday_start",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Начало Понедельника"
            ),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="saturday_end",
            field=models.TimeField(blank=True, null=True, verbose_name="Конец Субботы"),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="saturday_start",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Начало Субботы"
            ),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="sunday_end",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Конец Воскресенья"
            ),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="sunday_start",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Начало Воскресенья"
            ),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="thursday_end",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Конец Четверга"
            ),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="thursday_start",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Начало Четверга"
            ),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="tuesday_end",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Конец Вторника"
            ),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="tuesday_start",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Начало Вторника"
            ),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="wednesday_end",
            field=models.TimeField(blank=True, null=True, verbose_name="Конец Среды"),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="wednesday_start",
            field=models.TimeField(blank=True, null=True, verbose_name="Начало Среды"),
        ),
    ]
