# Generated by Django 4.2.8 on 2024-05-05 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_alter_company_options_alter_contact_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workschedule",
            options={
                "verbose_name": "Рабочее время",
                "verbose_name_plural": "Рабочее время",
            },
        ),
    ]
