# Generated by Django 4.2.8 on 2024-05-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_facebook_company_instagram_company_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='facebook',
            field=models.URLField(blank=True, db_column='facebook_company', null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='company',
            name='instagram',
            field=models.URLField(blank=True, db_column='insta_company', null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, db_column='website_company', null=True, verbose_name='Веб-сайт'),
        ),
        migrations.AlterField(
            model_name='company',
            name='whatsapp',
            field=models.URLField(blank=True, db_column='whats_company', null=True, verbose_name='WhatsApp'),
        ),
    ]
