# Generated by Django 4.2.8 on 2024-06-14 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_remove_promotion_user_promotion_user'),
        ('company', '0006_alter_company_facebook_alter_company_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='category_of_company', to='promotion.promotioncategory', verbose_name='категория компании'),
            preserve_default=False,
        ),
    ]
