# Generated by Django 4.2.8 on 2024-10-20 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0007_remove_promotion_user_promotion_user'),
        ('company', '0008_alter_contact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_of_company', to='promotion.promotioncategory', verbose_name='категория компании'),
        ),
    ]
