# Generated by Django 4.2.8 on 2024-02-05 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_promotions', to=settings.AUTH_USER_MODEL),
        ),
    ]
