# Generated by Django 4.2.8 on 2023-12-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_remove_promotion_new_price_promotion_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='type',
            field=models.CharField(choices=[('discount', 'Скидка'), ('bonus', 'Бонус'), ('certificate', 'Сертификат')], default='DISCOUNT', max_length=45),
        ),
    ]
