# Generated by Django 4.2.8 on 2024-01-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_alter_promotion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='type',
            field=models.CharField(choices=[('Discount', 'Скидка'), ('Bonus', 'Бонус'), ('Certificate', 'Сертификат')], default='Discount', max_length=45),
        ),
    ]
