# Generated by Django 4.2.8 on 2024-01-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0006_delete_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'promotion', 'verbose_name_plural': 'promotions'},
        ),
        migrations.AlterModelTable(
            name='promotion',
            table='promotion',
        ),
    ]
