# Generated by Django 4.2.8 on 2024-01-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0007_alter_promotion_options_alter_promotion_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotioncategory',
            options={'verbose_name': 'promotion_category', 'verbose_name_plural': 'promotion_categories'},
        ),
        migrations.AlterModelTable(
            name='promotioncategory',
            table='promotion_category',
        ),
    ]
