# Generated by Django 4.2.8 on 2024-01-30 12:55

from django.db import migrations, models
import promotion.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0008_alter_promotioncategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncategory',
            name='image',
            field=models.ImageField(null=True, upload_to=promotion.utils.utils.category_image_path),
        ),
    ]
