# Generated by Django 4.2.8 on 2024-02-01 09:16

from django.db import migrations, models
import promotion.models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0009_promotioncategory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='old_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount',
            field=models.PositiveIntegerField(null=True, validators=[promotion.models.validate_discount]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(upload_to='promotion/%Y-%m-%d/'),
        ),
    ]
