# Generated by Django 4.2.8 on 2024-02-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0011_promotion_is_daily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='start_date',
        ),
    ]
