# Generated by Django 4.2.8 on 2024-02-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0012_remove_promotion_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='price',
            new_name='new_price',
        ),
        migrations.AddField(
            model_name='promotion',
            name='old_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
