# Generated by Django 4.2.8 on 2024-02-01 18:06

import django.core.validators
from django.db import migrations, models
import promotion.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0013_rename_price_promotion_new_price_promotion_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncategory',
            name='icon',
            field=models.FileField(null=True, upload_to=promotion.utils.utils.category_icon_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
