# Generated by Django 4.2.8 on 2024-02-04 19:30

import company.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotion', '0014_promotioncategory_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=company.utils.utils.company_image_path)),
                ('discounts', models.PositiveIntegerField()),
                ('promotions', models.ManyToManyField(related_name='promotions', to='promotion.promotion')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'db_table': 'company',
            },
        ),
    ]
