# Generated by Django 4.2.8 on 2024-02-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
