# Generated by Django 4.2.8 on 2024-02-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_alter_promotion_type'),
        ('company', '0002_company_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='promotion',
        ),
        migrations.AddField(
            model_name='company',
            name='promotion',
            field=models.ManyToManyField(related_name='promotion', to='promotion.promotion'),
        ),
    ]
