# Generated by Django 4.2.8 on 2024-02-01 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_alter_promotion_type'),
        ('company', '0003_remove_company_promotion_company_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='promotion',
        ),
        migrations.AddField(
            model_name='company',
            name='promotion',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='promotion.promotion'),
            preserve_default=False,
        ),
    ]
