# Generated by Django 4.2.8 on 2024-02-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_alter_promotion_type'),
        ('company', '0005_alter_company_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='promotion',
        ),
        migrations.AddField(
            model_name='company',
            name='promotions',
            field=models.ManyToManyField(related_name='companies', to='promotion.promotion'),
        ),
    ]
