# Generated by Django 4.2.8 on 2024-02-04 18:34

import company.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0014_promotioncategory_icon'),
        ('company', '0006_remove_company_promotion_company_promotions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='title',
        ),
        migrations.AddField(
            model_name='company',
            name='discounts',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(upload_to=company.utils.utils.company_image_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='promotions',
            field=models.ManyToManyField(related_name='promotions', to='promotion.promotion'),
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
