# Generated by Django 4.2.8 on 2024-01-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table='user',
        ),
    ]
